- dockerfiles/registrar.Dockerfile
This PR includes the strategy for the cache to handle dependencies download.
> perf: optimised to handle dependecies cache

- .github/workflows/push-enterprise-catalog-image.yaml
- dockerfiles/enterprise-catalog.Dockerfile
**Issue:** https://github.com/edx/public-dockerfiles/issues/16
PR adds `Dockerfile` along with workflow to build & push docker image for `enterprise-subsidy`.
> feat: added dockerfile and docker image push workflow for enterprise-catalog

- .github/workflows/push-xqueue-image.yaml
- dockerfiles/xqueue.Dockerfile
**Issue:** https://github.com/edx/public-dockerfiles/issues/17
PR adds `Dockerfile` along with workflow to build & push docker image for `xqueue`.
> feat: added dockerfile and docker image push workflow for xqueue

- .github/workflows/push-edx-analytics-data-api-image.yaml
- dockerfiles/edx-analytics-data-api.Dockerfile
**Related issue**
https://github.com/edx/public-dockerfiles/issues/18
> Add workflow and dockerfile for edx-analytics-data-api

- .github/workflows/push-edx-analytics-dashboard-image.yaml
- dockerfiles/edx-analytics-dashboard.Dockerfile
**Issue:** https://github.com/edx/public-dockerfiles/issues/19
PR adds `Dockerfile` along with workflow to build & push docker image for `edx-analytics-dashboard`.
> feat: added dockerfile and docker image push workflow for edx-analytics-dashboard

- .github/workflows/push-commerce-coordinator-image.yaml
- dockerfiles/commerce-coordinator.Dockerfile
**Issue:** https://github.com/edx/public-dockerfiles/issues/22
PR adds `Dockerfile` along with workflow to build & push docker image for `commerce-coordinator`.
> feat: added dockerfile and docker image push workflow for commerce-coordinator

- .github/workflows/push-course-discovery-image.yaml
- dockerfiles/course-discovery.Dockerfile
**Description**
This PR adds Dockerfile and workflow to push the image for course discovery in the repo.
**Issue Link**
https://github.com/edx/public-dockerfiles/issues/4
> Migrate discovery dockerfile setup

- .github/workflows/push-edx-exams-image.yaml
- dockerfiles/edx-exams.Dockerfile
**Related issue**
- https://github.com/edx/public-dockerfiles/issues/23
**Tested on docker hub**
> Add workflow and dockerfile for edx-exams

- dockerfiles/portal-designer.Dockerfile
**Issue:** https://github.com/edx/public-dockerfiles/issues/26
PR adds `Dockerfile` for `portal-designer`.
Note: Workflow to push the image (`push-docker-image.yml`) does not exist for `portal-designer`
> feat: added portal-designer  Dockerfile

- .github/workflows/push-enterprise-access-image.yaml
- dockerfiles/enterprise-access.Dockerfile
- It was identified during workflows consolidation [task](https://github.com/edx/public-dockerfiles/issues/43) that enterprise-access workflow had been failing due to permission issues with requirements files so updated the paths to handle the issue.
> fix: corrected requirements dir path

- .github/workflows/push-edx-notes-api-image.yaml
- dockerfiles/edx-notes-api.Dockerfile
- `edx-notes-api` repository has dropped support for `Python 3.8` which caused the docker-publish workflow to fail.
- Updated the `Dockerfile` to use `Python 3.12` to fix the failing build
- Tested the workflow on the PR to successfully build and push a test image
> edx notes api Dockerfile Python 3.12 upgrade

- dockerfiles/edx-notes-api.Dockerfile
- Updated `edx-notes-api` Dockerfile to include `WORKDIR` to fix the path issues..
> build: fix edx-notes-api workdir in Dockerfile

- dockerfiles/edx-notes-api.Dockerfile
- Reverted the refactoring mistakenly done on the `RUN` command instead of only `ARG` and `ENV` variable declarations.
> fix: fix Dockerfile run command

- .github/workflows/push-license-manager-image.yaml
- dockerfiles/license-manager.Dockerfile
**Issue:** https://github.com/openedx/license-manager/issues/736
PR adds Dockerfile along with workflow to build & push docker image for  `license-manager`.
> feat: added dockerfile and docker image push workflow for license-manager 

- .github/workflows/push-license-manager-image.yaml
- dockerfiles/enterprise-catalog.Dockerfile
- dockerfiles/enterprise-subsidy.Dockerfile
- Updated Dockerfiles for `enterprise-catalog` and `enterprise-subsidy` to include `WORKDIR` in it
- Adding this path should resolve the `gunicorn` and `manage.py` issues in the container
- Updated `license-manager` IDA image workflow to push for both platforms similar to the other enterprise IDAs.
> build: update WORKDIR in enterprise IDAs

- dockerfiles/enterprise-catalog.Dockerfile
- dockerfiles/enterprise-subsidy.Dockerfile
- `mkdir` for requirements needs to be placed after the `WORKDIR` declaration for the paths to be functional.
> fix: fix commands order in dockerfiles

- dockerfiles/enterprise-catalog.Dockerfile
Reverts edx/public-dockerfiles#61
The PATH update has already been handled everywhere else so we don't need this change now as fixing this now will need us to revert all those pipeline changes in ArgoCD and edx-internal pipelines (see [thread](https://twou.slack.com/archives/C0495EETUVC/p1731942876492789))
> Revert "fix: update enterprise-catalog WORKDIR"

- dockerfiles/course-discovery.Dockerfile
- dockerfiles/credentials.Dockerfile
- dockerfiles/ecommerce.Dockerfile
- dockerfiles/edx-analytics-dashboard.Dockerfile
- dockerfiles/edx-analytics-data-api.Dockerfile
- dockerfiles/edx-notes-api.Dockerfile
- dockerfiles/registrar.Dockerfile
- dockerfiles/xqueue.Dockerfile
This PR is to be merged when the [issue for devstack migration](https://github.com/edx/devstack/issues/68) closes. 
We are pulling devstack.py file from devstack repository as it will be removed from the repository of all the IDAs itself.
> chore: add devstack.py file in dockerfiles

- dockerfiles/license-manager.Dockerfile
**Related Issue**
- https://github.com/edx/devstack/issues/74
> chore: update user permissions in license manager

- dockerfiles/enterprise-catalog.Dockerfile
- Removing the `distutils` installation from dockerfile to fix the ongoing build failure
> build: remove distuils installation in Dockerfile

- .github/workflows/push-course-discovery-image.yaml
- dockerfiles/course-discovery.Dockerfile
- dockerfiles/edx-exams.Dockerfile
- dockerfiles/edx-notes-api.Dockerfile
- dockerfiles/enterprise-access.Dockerfile
- dockerfiles/enterprise-subsidy.Dockerfile
- dockerfiles/license-manager.Dockerfile
- dockerfiles/portal-designer.Dockerfile
- dockerfiles/program-intent-engagement.Dockerfile
- dockerfiles/registrar.Dockerfile
- Python 3.12.8 has [dropped](https://www.python.org/downloads/release/python-3128/) the deprecated distutils module which has caused some pipelines build to fail.
> chore: removed distutils package from dockerfiles

- dockerfiles/credentials.Dockerfile
Updating ubuntu to 24.01 and npm to 10 and node to 20.17.
Verified that it builds and runs without a problem.
FIXES: APER-3706
> chore: updating os version for credentials

- .github/workflows/push-designer-image.yaml
Workflow to push image of `portal-designer` wasn't included initially. Now that this has been added to `devstack` it's crucial to push the image to reference the image from `edxops` registry. 
This PR adds the workflow to push `portal-designer` image to dockerhub
> chore: added workflow to push portal-designer image

- .github/workflows/push-docker-images.yml
- dockerfiles/codejail.Dockerfile
- images-data.json
This is just a skeleton image and doesn't have any directories or packages that are specific to codejail yet.
Lots of differences from cookiecutter django-ida default:
- Remove MySQL system packages
- Use latest Ubuntu LTS
- Shorten the base folder from `codejail-service` to `codejail`
- Use port 8080; we'll remap it in compose anyhow
- Use ADD on a git repo rather than RUN/curl/tar, which runs afoul of Docker caching when a branch is used.
- Allow selecting a commit version
- Pass `DJANGO_SETTINGS_MODULE` from outside as env var to reduce differences between dev and prod targets and add flexibility.
- Install in /app and create virtualenv in /venv; no need to hew to the same pattern we used in the configuration repo.
- Remove apt cache in same RUN command so as not to create a fat layer …
> feat: Add codejail service

- images-data.json
- After the consolidation of workflows, updating the architecture platforms for the devstack images to be available on all platforms. 
- This will resolve following error when setting up devstack or pulling images locally 
```
no matching manifest for linux/amd64 in the manifest list entries
make: *** [dev.pull.credentials+discovery+ecommerce+edx_notes_api+forum+frontend-app-authn+frontend-app-gradebook+frontend-app-payment+frontend-app-publisher+frontend-app-learning+lms+cms] Error 18
```
> build: update platforms OS for all docker images

- .github/workflows/push-docker-images.yml
- images-data.json
This PR adds owning team email in images data on which an email alert will be sent in case of failure of workflow. It also adds link to troubleshooting guidelines in email body.
> chore: add owning team emails and document link

- images-data.json
Follow up to https://2u-internal.atlassian.net/browse/COSMO-626, removing extraneous "lms-production" and "cms-production" images, as don't actually end up being used for deployments to production.
> chore: remove unecessary prod images

- dockerfiles/codejail.Dockerfile
I am encountering a failure in the GoCD build process due to a Dockerfile parsing error:
```failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 30: unknown instruction: APT-GET```
To address this issue, I have restructured the Dockerfile by replacing the heredoc syntax with a standard multi-line RUN instruction, ensuring that each line is properly terminated with a backslash (\) for line continuation
> fix: Replace heredoc with multi-line RUN instruction

- dockerfiles/codejail.Dockerfile
Tweaks following https://github.com/edx/public-dockerfiles/pull/94
- Restore comment
- Restore line breaks
> docs: Restore comment and formatting in RUN command for codejail

- dockerfiles/codejail.Dockerfile
A collection of improvements to enable the usual live-reloading workflow. Running as app meant we couldn't recompile files, modify the container environment, etc.
- Run as root in dev target, for convenience and matching other images
- Use gunicorn for both targets, since in devstack we can specify the CMD in the docker-compose file anyhow.
- Install make, less, and some editors in the dev target
- Set up virtualenv for dev environment
> feat: Various codejail improvements for devstack usage

- dockerfiles/codejail-service.Dockerfile
- Install Python 3.8 from deadsnakes for sandbox Python
- Install depencies for use inside sandbox
- Install sudo for entering sandbox
- Document relationship to codejail's docs
Also, some cleanup:
- Rename args `GITHUB_REPO` to `APP_REPO` and `VERSION` to `APP_VERSION` to help distinguish from sandbox args
- Similarly, rename `PYVER` to `APP_PY_VER` for clarity
> feat: Set up sandbox environment inside codejail image

- apparmor/README.rst
- apparmor/openedx_codejail_service.profile
This is preparatory for deploying to stage.
Two commits (see messages for details):
- Copy profile from devstack, unchanged
- Adjust profile and add docs
See corresponding devstack PR: https://github.com/edx/devstack/pull/117
> Add apparmor profile for codejail-service

- dockerfiles/codejail-service.Dockerfile
This will allow the helm chart to call `ddtrace-run` without knowing where the binary is located.
> fix: Set PATH for all codejail dockerfile targets

- dockerfiles/codejail-service.Dockerfile
- Don't bother deleting `ubuntu` user, as we won't be needing the UID 1000 any more.
- While we're in these lines, remove unneeded braces from variable interpolation. They just create longer lines, here, and aren't actually needed for delimiting.
- Don't create user home for app user -- wasn't needed.
Part of https://github.com/edx/edx-arch-experiments/issues/983 and see https://github.com/openedx/codejail-service/pull/30 for new docs.
> fix!: Use new, non-colliding UID and GID for codejail app, sandbox users

- apparmor/openedx_codejail_service.profile
A lot of the new pods are in an attempting-termination status with hundreds of the following `FailedKillPod` error event:
`unknown error after kill: runc did not terminate successfully: exit status 1: unable to signal init: permission denied`
I believe the issue is that the outer profile does not allow for receiving signals. Hopefully this will fix it.
> feat: Allow codejail-service webapp to receive kill signal

- dockerfiles/edx-platform.Dockerfile
- In the previous PR `$CONFIG_ROOT` variable was removed which caused the env paths to be wrong and caused following error when setting up devstack
```
py38-django32-migrate: commands succeeded
congratulations :)
docker compose exec lms bash -c 'source /edx/app/edxapp/edxapp_env && cd /edx/app/edxapp/edx-platform/ && make migrate-lms'
python manage.py lms showmigrations --database default --traceback --pythonpath=.
Traceback (most recent call last):
File "/edx/app/edxapp/edx-platform/manage.py", line 99, in <module>
execute_from_command_line([sys.argv[0]] + django_args)
File "/edx/app/edxapp/venvs/edxapp/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
utility.execute()
File …
```
> fix: fix config path in edxapp dockerfile

- dockerfiles/credentials.Dockerfile
We are currently still installing Node 18 and npm 9.x when creating an image for the Credentials IDA. Node 18 is officially EOL on April 30th, 2025.
This PR updates the version of Node and NPM to their latest respective versions for Node 20.x.
> chore: update Node to v20.x and npm to 11.x in Credentials Dockerfile

- dockerfiles/edx-platform.Dockerfile
While running the `npm run compile-sass` command needs the `libsass` dependency, which was moved to `assets.txt`.
This fixes one of the errors faced in the https://github.com/edx/edx-arch-experiments/issues/992
> fix: install assets.txt in edx-platform Dockerfile

- dockerfiles/codejail-service.Dockerfile
We'll want to pass in codejail-service and edx-platform commit hashes in the builder, and that requires switching from RUN to ADD. This will also avoid stale cache issues around RUN commands that don't contain arg references.
Breaking changes:
- Use `CODEJAIL_SERVICE_REPO` instead of `APP_REPO` for consistency with other repos. Same for `APP_VERSION`.
- Split `SANDBOX_DEPS_PATH` into two parts to accommodate ADD, which requires a directory instead of a direct file path.
- Remove `SAND_DEPS` arg, which doesn't need to be a build arg at all. It's only used on two consecutive lines and is internal only.
Also:
- Stop installing curl, as it is no longer needed for building the image
- Move WORKDIR line to after the ADD that unpacks a repository there, just because it seems to make more sense …
> feat!: Use ADD for codejail in prep for passing in commit hashes

- dockerfiles/codejail-service.Dockerfile
This is part of https://github.com/edx/edx-arch-experiments/issues/912
Once teak is released, we can change to teak.txt, but that's still a few days out.
> feat: Upgrade codejail sandbox to Python 3.12 and sumac deps

- dockerfiles/codejail-service.Dockerfile
Teak has now been released, so we can use the newer lockfile.
> feat: Switch codejail-service sandbox deps to teak

- dockerfiles/codejail-service.Dockerfile
We've decided not to push for the 3.12 upgrade yet, and will proceed with the full cutover to remote codejail. Later, we'll figure out how to upgrade the service's sandbox to 3.12/teak (or newer).
> revert: Downgrade codejail-service sandbox to 3.8/quince again

- dockerfiles/edx-exams.Dockerfile
This PR is adding `dev` build stage in edx-exams Dockerfile, as for devstack we shouldn't change the user from `root` to `user`, otherwise it will fail in installing requirements due to permission errors.
Related to, https://github.com/edx/devstack/issues/78
> feat: add dev build stage in edx-exams Dockerfile

- dockerfiles/credentials.Dockerfile
Dogfooding a recent change that allows us to repeatedly rebuild Docker images for our IDAs. See https://2u-internal.atlassian.net/wiki/spaces/~840928901/pages/1977483450/Building+docker+images+repeatably.
> feat: update Credentials Dockerfile to support repeated rebuilds

- dockerfiles/enterprise-catalog.Dockerfile
- dockerfiles/enterprise-subsidy.Dockerfile
- dockerfiles/license-manager.Dockerfile
Currently, this PR aims to resolve the failing build pipeline in enterprise-catalog by removing the installation of newrelic from the build process for `enterprise-catalog`
To avoid this error from occurring in similar builds in enterprise, I am removing references to installing newrelic in `enterprise-subsidy` and `license-manager`
Related ticket: https://github.com/edx/internal-dockerfiles/pull/180
> chore: remove newrelic installation from enterprise builds

- dockerfiles/commerce-coordinator.Dockerfile
Incorrect syntax : 
`CMD gunicorn --workers=2 --name commerce-coordinator -c /edx/app/commerce-coordinator/commerce_coordinator/docker_gunicorn_configuration.py --log-file - --max-requests=1000 commerce-coordinator.wsgi:application`
Fix:
`CMD gunicorn --workers=2 --name commerce-coordinator -c /edx/app/commerce-coordinator/commerce_coordinator/docker_gunicorn_configuration.py --log-file - --max-requests=1000 commerce_coordinator.wsgi:application`
> fix: correct CMD syntax in commerce-coordinator Dockerfile

- dockerfiles/edx-platform.Dockerfile
> fix: Use correct translations stage name in edxapp COPY

- dockerfiles/edx-platform.Dockerfile
devstack_docker was removed from edx-platform, and we want to use devstack instead.
> fix: Use devstack instead of devstack_docker.

- dockerfiles/edx-platform.Dockerfile
We were using this with the old devstack-experimental files. We can mount these in devstack without doing this hack.
> fix: Remove attempt to add minimal lms and cms files.

- dockerfiles/edx-platform.Dockerfile
This is required for BOMS-236 -- we need to start building the k8s images from the edx-platform-private repo to pick up any security patches.
- Add optional `EDX_PLATFORM_REPO` build arg defaulting to public repo
- Accept `GIT_AUTH_TOKEN` build secret and pass to curl calls (but don't require it when using public repo)
Also, make curl calls fail on 4XX errors using `-f/--fail`, and add `-sS` to reduce unwanted progress output.
> feat: Allow building edxapp from private repo

- dockerfiles/edx-platform.Dockerfile
Focal is out of support and so we can no longer install from deadsnakes. Trying jammy to see if anything breaks. If not, we can give it a shot in the EC2 version as well.
Package changes:
- Jammy has libssl3 instead of libssl1.1
BOMS-238
> feat: Try upgrading edxapp to Ubuntu 22.04 Jammy

- dockerfiles/course-discovery.Dockerfile
Upgrades the course-discovery Dockerfile base image from ubuntu:focal → ubuntu:jammy.
Verified local build inside Codespaces :
- python3 --version → 3.12.11
- pip --version → 25.2
> feat: course-discovery install jammy

- dockerfiles/credentials.Dockerfile
Inspired by the upgrade by Enterprise team (https://github.com/edx/public-dockerfiles/pull/171), it's possible that we needed to update Credentials IDA to a more recent version of Ubuntu in order to stay on a supported version.
> feat: credentials install ubuntu jammy
