.github/workflows/push-credentials-image.yaml
dockerfiles/credentials.Dockerfile

- Related Issue
https://github.com/edx/public-dockerfiles/issues/2

Add workflow and dockerfile for credentials

---

.github/workflows/push-credentials-image.yaml

Related PR:
- https://github.com/edx/public-dockerfiles/pull/8

Add platform variable for credentials workflow

---

.github/workflows/push-program-intent-engagement-image.yaml
dockerfiles/program-intent-engagement.Dockerfile

**Issue:** https://github.com/edx/public-dockerfiles/issues/24
PR adds `Dockerfile` along with workflow to build & push docker image for `program-intent-engagement`.

feat: added dockerfile and docker image push workflow for program-intent-engagement

---

.github/workflows/push-enterprise-subsidy-image.yaml
dockerfiles/enterprise-subsidy.Dockerfile

**Issue:** https://github.com/edx/public-dockerfiles/issues/13
PR adds `Dockerfile` along with workflow to build & push docker image for `enterprise-subsidy`.

feat: added dockerfile and docker image push workflow for enterprise-subsidy

---

.github/workflows/push-enterprise-access-image.yaml
dockerfiles/enterprise-access.Dockerfile

**Issue:** https://github.com/edx/public-dockerfiles/issues/13
PR adds `Dockerfile` along with workflow to build & push docker image for `enterprise-access`.

feat: added dockerfile and docker image push workflow for enterprise-access

---

.github/workflows/push-course-discovery-image.yaml
.github/workflows/push-edx-exams-image.yaml
dockerfiles/commerce-coordinator.Dockerfile
dockerfiles/course-discovery.Dockerfile
dockerfiles/credentials.Dockerfile
dockerfiles/ecommerce.Dockerfile
dockerfiles/edx-analytics-dashboard.Dockerfile
dockerfiles/edx-analytics-data-api.Dockerfile
dockerfiles/edx-exams.Dockerfile
dockerfiles/edx-notes-api.Dockerfile
dockerfiles/enterprise-access.Dockerfile
dockerfiles/enterprise-catalog.Dockerfile
dockerfiles/enterprise-subsidy.Dockerfile
dockerfiles/portal-designer.Dockerfile
dockerfiles/registrar.Dockerfile
dockerfiles/xqueue.Dockerfile

This PR resolves warnings raised by Github actions during image build. 
https://github.com/edx/public-dockerfiles/actions/runs/11472835687

chore: fix github warnings in Dockerfiles

---

.github/workflows/push-enterprise-access-image.yaml
.github/workflows/push-enterprise-catalog-image.yaml
.github/workflows/push-enterprise-subsidy-image.yaml

- Updated the platforms in the enterprise IDAs i.e. `enterprise-access`, `enterprise-subsidy` and `enterprise-catalog` to resolve the platform issues locally for developers.

build: update enterprise IDA image platforms

---

dockerfiles/enterprise-catalog.Dockerfile

- Updated WORKDIR path according to the paths being used previously.

fix: update enterprise-catalog WORKDIR

---

.github/workflows/push-license-manager-image.yaml

fix: change license manager target

---

.github/workflows/push-edx-exams-image.yaml

**Description**
Add platform variable for edx-exams workflow to add support for linux/arm64/v8 (m1/m2 mac) machines.

Add platform variable for edx-exams workflow

---

.github/workflows/push-course-discovery-image.yaml
dockerfiles/course-discovery.Dockerfile

- PR created under the issue https://github.com/edx/public-dockerfiles/issues/67

Update course discovery docekrfile config

---

dockerfiles/commerce-coordinator.Dockerfile

Updated python version from `3.8` to `3.12` in `commerce-coordinator` image as we are updating python version in `commerce-coordinator `repo.

chore: [commerce-coordinator] update python version in dockerfile

---

.github/workflows/push-edx-analytics-dashboard-image.yaml
dockerfiles/edx-analytics-dashboard.Dockerfile

- edx-analytics-dashboard service Python 3.12 Upgrade
- Tested the service by triggering the image publish workflow on the PR successfully.

Insights python312 upgrade

---

dockerfiles/credentials.Dockerfile

Reverts edx/public-dockerfiles#74
See PR # https://2u-internal.atlassian.net/browse/APER-3837 for details. `django-static18n` breaks for us on noble.

Revert "chore: updating os version for credentials"

---

.github/workflows/push-docker-images.yml
images-data.json

https://2u-internal.atlassian.net/browse/COSMO-626
This PR is being made to fix the `edxapp-consumer-worker` deployment pipeline. It looks like we've had a `edx-platform` Dockerfile in public-dockerfiles for local dev, so we plan to merge this PR which will add a Dockerfile for stage & prod.

feat: add prod images to push for edx-platform

---

.github/workflows/push-docker-images.yml
images-data.json

Correction of lms&cms image names from: https://github.com/edx/public-dockerfiles/pull/83

fix: correct names for lms/cms images

---

.github/workflows/push-docker-images.yml

Testing a build/push here for enterprise-access: https://github.com/edx/public-dockerfiles/actions/runs/13015449901
https://hub.docker.com/r/edxops/enterprise-access-dev/tags

build: tag latest images

---

README.md

This PR adds readme file documenting repo details
issue link: https://github.com/edx/public-dockerfiles/issues/88

chore: add readme file for the repo

---

.github/workflows/push-docker-images.yml
README.rst

I renamed the image in be63a6b40827 but missed this location. (The readme had the wrong name as well.)

build: Update codejail name in workflow file; update readme too

---

README.rst

This was mostly Markdown syntax with some rST.

docs: Fix syntax in README

---

.github/workflows/check-image-list-sync.yml
.github/workflows/push-docker-images.yml

Also, fix a mismatch. (See second commit's description for details.)
- Failing build before the mismatch was resolved: https://github.com/edx/public-dockerfiles/actions/runs/13418747664?pr=105
- Passing build after the fix: https://github.com/edx/public-dockerfiles/actions/runs/13418787745?pr=105

build: Add CI check that image-data and workflow lists are in sync

---

dockerfiles/credentials.Dockerfile

Updates the Credentials IDA's Dockerfile to install and use Python 3.12. We are also in the process of upgrading the Python version used by CI for the Credentials service too.
We also update the version of node to the latest version of Node 18 LTS (18.17.1 -> 18.20.7).
Included are minor updates and readability improvements so that this file is more in line with Dockerfiles for our other services.

feat: update Credentials docker image to use Python 3.12

---

dockerfiles/edx-platform.Dockerfile

- Remove the deprecated `CONFIG_ROOT`
- Add missing `NODE_PATH`

chore: update environment variables

---

dockerfiles/edx-platform.Dockerfile

This helps ensure that these files are where they
need to be for collectstatic.
https://github.com/edx/edx-arch-experiments/issues/992

feat: Ensure that the vendor JS and CSS are built.

---

dockerfiles/edx-platform.Dockerfile

This doesn't yet support proper caching when a branch is passed in, but we should now be able to pass in a commit during GoCD builds, and the default behavior is no worse than before (in terms of caching).

feat: Allow consistent builds for edx-platform

---

.github/workflows/push-docker-images.yml
README.rst
dockerfiles/order-fulfillment.Dockerfile
images-data.json

This PR adds a docker file for https://github.com/edx/order-fulfillment/ service

chore: add dockerfile for order-fulfillment

---

dockerfiles/order-fulfillment.Dockerfile

Changed the path of files to cater master branch instead of main

fix: path for order-fulfillment

---

dockerfiles/program-intent-engagement.Dockerfile

fixing the  broken deployment by updating the Python version correctly.
FIXES: APER-3937

chore:  fixing the PIE Python version

---

dockerfiles/program-intent-engagement.Dockerfile

when adding the new venv  structure, I left in the old one.

chore:  fix broken pie venv

---

dockerfiles/edx-platform.Dockerfile

Restoring the rest of the step to see if this still reproduces the error.

feat: Restore pull_translations in edxapp

---

dockerfiles/credentials.Dockerfile

following the steps in https://2u-internal.atlassian.net/wiki/spaces/~840928901/pages/1977483450/Building+docker+images+repeatably
FIXES: APER-3998

feat: build docker images repeatably

---

dockerfiles/credentials.Dockerfile

* adds a `$` which was preventing the settings file from pulling
* removed repeated installation of translations pull

chore: fixing bug in credentials

---

dockerfiles/edx-platform.Dockerfile

Move `*_VERSION` ARGs to global scope, and redeclare them at just before they're first needed. This allows the cache of `minimal-system` and the first part of `builder-production` to remain valid even when the repo revisions have changed, which should speed up builds.
We've already done something similar for the internal dockerfile.
Also:
- Explain why `DEBIAN_FRONTEND` is an ARG instead of an ENV.
- Remove `NO_PREREQ_INSTALL`, since paver has been removed.
- Two newlines before each stage, for readability.
- Expand comments on some stages.

feat: Improve caching for edx-platform (move version ARGs up)
